workflows:
  ios-workflow:
    name: iOS Build (App Store - Manual Signing Fully Self-Contained)
    max_build_duration: 60

    environment:
      node: latest
      xcode: latest
      cocoapods: default
      groups:
        - ios_signing
      vars:
        TEAM_ID: "CKDUJJL6BZ"
        BUNDLE_ID: "com.donal.nextstepai"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install cert + profile (from env vars)
        script: |
          set -euo pipefail

          : "${IOS_CERT_P12_B64:?Missing IOS_CERT_P12_B64}"
          : "${IOS_CERT_PASSWORD:?Missing IOS_CERT_PASSWORD}"
          : "${IOS_PROFILE_B64:?Missing IOS_PROFILE_B64}"

          keychain initialize

          echo "$IOS_CERT_P12_B64" | base64 --decode > /tmp/cert.p12
          keychain add-certificates --certificate /tmp/cert.p12 --certificate-password "$IOS_CERT_PASSWORD"

          PROFILE_TMP="/tmp/profile.mobileprovision"
          echo "$IOS_PROFILE_B64" | base64 --decode > "$PROFILE_TMP"

          PROFILE_PLIST="$(security cms -D -i "$PROFILE_TMP")"
          UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$PROFILE_PLIST")
          NAME=$(/usr/libexec/PlistBuddy -c 'Print :Name' /dev/stdin <<< "$PROFILE_PLIST" || true)
          APP_ID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' /dev/stdin <<< "$PROFILE_PLIST" || true)

          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILE_DIR"
          cp "$PROFILE_TMP" "$PROFILE_DIR/$UUID.mobileprovision"

          echo "Installed provisioning profile:"
          echo "  UUID: $UUID"
          echo "  Name: ${NAME:-<unknown>}"
          echo "  AppID: ${APP_ID:-<unknown>}"

          echo "=== SIGNING IDENTITIES ==="
          security find-identity -v -p codesigning || true
          echo "=== PROFILES ==="
          ls -la "$PROFILE_DIR" || true

          echo "PROFILE_UUID=$UUID" >> "$CM_ENV"

      - name: Create exportOptions.plist
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOF

      - name: Build iOS app (archive)
        script: |
          set -euo pipefail

          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="${PROFILE_UUID}" \
            archive

      - name: Export IPA
        script: |
          set -euo pipefail

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/export

    artifacts:
      - build/export/*.ipa
      - build/**/*.xcarchive
      - exportOptions.plist
