workflows:
  ios-workflow:
    name: iOS Build (App Store - Codemagic Signing)
    max_build_duration: 60

    environment:
      node: latest
      xcode: latest
      cocoapods: default
      vars:
        TEAM_ID: "CKDUJJL6BZ"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Install signing assets (Codemagic)
        script: |
          set -euo pipefail
          keychain initialize
          keychain add-certificates
          xcode-project use-profiles --verbose

          echo "=== SIGNING IDENTITIES ==="
          security find-identity -v -p codesigning || true

          echo "=== PROVISIONING PROFILES ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

          # Fail hard if Codemagic did not inject signing assets
          IDS="$(security find-identity -v -p codesigning 2>/dev/null | grep -c 'valid identities found' || true)"
          COUNT="$(ls -1 "$HOME/Library/MobileDevice/Provisioning Profiles"/*.mobileprovision 2>/dev/null | wc -l | tr -d ' ')"
          if [ "$COUNT" = "0" ]; then
            echo "ERROR: No provisioning profiles installed. Codemagic did not inject code signing assets into this build."
            exit 1
          fi

      - name: Build iOS app (archive)
        script: |
          set -euo pipefail
          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            archive

      - name: Export IPA
        script: |
          set -euo pipefail

          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
          </dict>
          </plist>
          EOF

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/export

    artifacts:
      - build/export/*.ipa
      - build/**/*.xcarchive
      - exportOptions.plist
