workflows:
  ios-workflow:
    name: iOS Build (App Store - Manual Signing)
    max_build_duration: 60

    environment:
      node: latest
      xcode: latest
      cocoapods: default

      # IMPORTANT:
      # Put IOS_CERT_P12_B64, IOS_CERT_PASSWORD, IOS_PROFILE_B64 into this Codemagic Variable Group
      groups:
        - ios-signing

      vars:
        TEAM_ID: "CKDUJJL6BZ"
        BUNDLE_ID: "com.donal.nextstepai"
        PROFILE_NAME: "nextstep-ai-appstore"

    scripts:
      - name: Debug environment (names only)
        script: |
          echo "WORKFLOW + BRANCH:"
          echo "CM_WORKFLOW_NAME=${CM_WORKFLOW_NAME:-}"
          echo "CM_BRANCH=${CM_BRANCH:-}"
          echo "CM_PULL_REQUEST=${CM_PULL_REQUEST:-}"
          echo "CM_REPO_SLUG=${CM_REPO_SLUG:-}"

          echo "IOS VARS PRESENT (names only):"
          env | cut -d= -f1 | sort | grep -E '^IOS_' || true

      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Import signing certificate + provisioning profile
        script: |
          set -euo pipefail

          : "${IOS_CERT_P12_B64:?Missing IOS_CERT_P12_B64}"
          : "${IOS_CERT_PASSWORD:?Missing IOS_CERT_PASSWORD}"
          : "${IOS_PROFILE_B64:?Missing IOS_PROFILE_B64}"

          keychain initialize

          # Import cert (.p12)
          echo "$IOS_CERT_P12_B64" | base64 --decode > /tmp/cert.p12
          keychain add-certificates --certificate /tmp/cert.p12 --certificate-password "$IOS_CERT_PASSWORD"

          # Install provisioning profile
          mkdir -p "$HOME/Library/MobileDevice/Provisioning Profiles"
          echo "$IOS_PROFILE_B64" | base64 --decode > "$HOME/Library/MobileDevice/Provisioning Profiles/${PROFILE_NAME}.mobileprovision"

          echo "=== SIGNING IDENTITIES ==="
          security find-identity -v -p codesigning || true
          echo "=== PROFILES ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: Create exportOptions.plist
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key>
              <string>${PROFILE_NAME}</string>
            </dict>
          </dict>
          </plist>
          EOF

      - name: Build iOS app (archive + export)
        script: |
          set -euo pipefail

          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PROVISIONING_PROFILE_SPECIFIER="${PROFILE_NAME}" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            archive

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/export

    artifacts:
      - build/export/*.ipa
      - build/**/*.xcarchive
      - exportOptions.plist
