workflows:
  ios-workflow:
    name: iOS Build (App Store)
    max_build_duration: 60

    environment:
      node: latest
      xcode: latest
      cocoapods: default

      vars:
        TEAM_ID: "CKDUJJL6BZ"
        BUNDLE_ID: "com.donal.nextstepai"
        PROFILE_NAME: "nextstep-ai-appstore"

      ios_signing:
        distribution_type: app_store
        bundle_identifier: "com.donal.nextstepai"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Set up code signing (Codemagic)
        script: |
          set -e
          keychain initialize
          xcode-project use-profiles

          echo "=== SIGNING IDENTITIES (after setup) ==="
          security find-identity -v -p codesigning || true
          echo "======================================="

      - name: Create exportOptions.plist
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store-connect</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>compileBitcode</key>
            <false/>
          </dict>
          </plist>
          EOF

      - name: Build iOS app (archive + export)
        script: |
          set -euo pipefail

          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            archive

          echo "=== SIGNING IDENTITIES (before export) ==="
          security find-identity -v -p codesigning || true
          echo "========================================="

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/export

    artifacts:
      - build/export/*.ipa
      - build/**/*.xcarchive
      - exportOptions.plist
