workflows:
  ios-workflow:
    name: iOS Build (App Store - Codemagic Signing + UUID)
    max_build_duration: 60

    environment:
      node: latest
      xcode: latest
      cocoapods: default
      vars:
        TEAM_ID: "CKDUJJL6BZ"
        BUNDLE_ID: "com.donal.nextstepai"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Apply Codemagic code signing (force install profiles/certs)
        script: |
          set -euo pipefail
          keychain initialize

          # This is the critical step: it pulls the cert/profile you've uploaded in Codemagic UI
          # and wires them into the Xcode project.
          xcode-project use-profiles --verbose

          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILE_DIR"

          echo "=== PROFILES DIRECTORY (after use-profiles) ==="
          ls -la "$PROFILE_DIR" || true

          echo "=== SIGNING IDENTITIES ==="
          security find-identity -v -p codesigning || true

          # Hard fail early if Codemagic still didn't install profiles
          COUNT="$(ls -1 "$PROFILE_DIR"/*.mobileprovision 2>/dev/null | wc -l | tr -d ' ')"
          if [ "$COUNT" = "0" ]; then
            echo "ERROR: No provisioning profiles installed on the build machine."
            echo "Fix in Codemagic UI: ensure the App Store provisioning profile for ${BUNDLE_ID} is attached to this workflow/build and not blocked (e.g., PR build)."
            exit 1
          fi

      - name: Find installed provisioning profile UUID for bundle id
        script: |
          set -euo pipefail
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"

          echo "Looking for installed profile for ${BUNDLE_ID} in: ${PROFILE_DIR}"
          ls -la "$PROFILE_DIR" || true

          UUID=""
          for f in "$PROFILE_DIR"/*.mobileprovision; do
            [ -e "$f" ] || continue

            PLIST="$(security cms -D -i "$f")"
            APP_ID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' /dev/stdin <<< "$PLIST" 2>/dev/null || true)
            TEAM=$(/usr/libexec/PlistBuddy -c 'Print :TeamIdentifier:0' /dev/stdin <<< "$PLIST" 2>/dev/null || true)
            THIS_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$PLIST" 2>/dev/null || true)

            if [[ "$TEAM" == "${TEAM_ID}" && "$APP_ID" == "${TEAM_ID}.${BUNDLE_ID}" ]]; then
              UUID="$THIS_UUID"
              break
            fi
          done

          if [ -z "$UUID" ]; then
            echo "No matching installed profile found for ${TEAM_ID}.${BUNDLE_ID}"
            exit 1
          fi

          echo "Found profile UUID: $UUID"
          echo "PROFILE_UUID=$UUID" >> "$CM_ENV"

      - name: Build iOS app (archive)
        script: |
          set -euo pipefail

          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="${PROFILE_UUID}" \
            archive

      - name: Export IPA
        script: |
          set -euo pipefail

          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOF

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/export

    artifacts:
      - build/export/*.ipa
      - build/**/*.xcarchive
      - exportOptions.plist
