workflows:
  ios-workflow:
    name: iOS Build (App Store - Hard Forced Profile)
    max_build_duration: 60

    environment:
      node: latest
      xcode: latest
      cocoapods: default
      vars:
        TEAM_ID: "CKDUJJL6BZ"
        BUNDLE_ID: "com.donal.nextstepai"
        PROFILE_NAME: "nextstep-ai-appstore"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Setup signing (Codemagic)
        script: |
          set -euo pipefail
          keychain initialize
          xcode-project use-profiles --verbose

          echo "=== SIGNING IDENTITIES ==="
          security find-identity -v -p codesigning || true
          echo "=== PROFILES ==="
          ls -la "$HOME/Library/MobileDevice/Provisioning Profiles" || true

      - name: Create exportOptions.plist (explicit profile mapping)
        script: |
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>signingStyle</key>
            <string>manual</string>
            <key>provisioningProfiles</key>
            <dict>
              <key>${BUNDLE_ID}</key>
              <string>${PROFILE_NAME}</string>
            </dict>
          </dict>
          </plist>
          EOF

      - name: Build iOS app (archive) - force profile + distribution cert
        script: |
          set -euo pipefail

          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -sdk iphoneos \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            PRODUCT_BUNDLE_IDENTIFIER="${BUNDLE_ID}" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE_SPECIFIER="${PROFILE_NAME}" \
            archive

      - name: Export IPA
        script: |
          set -euo pipefail

          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/export

    artifacts:
      - build/export/*.ipa
      - build/**/*.xcarchive
      - exportOptions.plist
