workflows:
  ios-workflow:
    name: iOS Build (App Store - Manual Signing UUID)
    max_build_duration: 60

    environment:
      node: latest
      xcode: latest
      cocoapods: default
      vars:
        TEAM_ID: "CKDUJJL6BZ"

    scripts:
      - name: Install dependencies
        script: |
          npm install

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Find installed provisioning profile UUID for bundle id
        script: |
          set -euo pipefail
          BUNDLE_ID="com.donal.nextstepai"
          PROFILE_DIR="$HOME/Library/MobileDevice/Provisioning Profiles"

          echo "Looking for installed profile for $BUNDLE_ID in: $PROFILE_DIR"
          ls -la "$PROFILE_DIR" || true

          UUID=""
          for f in "$PROFILE_DIR"/*.mobileprovision; do
            [ -e "$f" ] || continue
            PLIST="$(security cms -D -i "$f")"
            APP_ID=$(/usr/libexec/PlistBuddy -c 'Print :Entitlements:application-identifier' /dev/stdin <<< "$PLIST" 2>/dev/null || true)
            TEAM=$(/usr/libexec/PlistBuddy -c 'Print :TeamIdentifier:0' /dev/stdin <<< "$PLIST" 2>/dev/null || true)
            THIS_UUID=$(/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< "$PLIST" 2>/dev/null || true)

            # APP_ID looks like TEAMID.com.bundle.id
            if [[ "$TEAM" == "${TEAM_ID}" && "$APP_ID" == "${TEAM_ID}.${BUNDLE_ID}" ]]; then
              UUID="$THIS_UUID"
              break
            fi
          done

          if [ -z "$UUID" ]; then
            echo "No matching installed profile found for ${TEAM_ID}.${BUNDLE_ID}"
            exit 1
          fi

          echo "Found profile UUID: $UUID"
          echo "PROFILE_UUID=$UUID" >> $CM_ENV

      - name: Build iOS app (archive)
        script: |
          set -euo pipefail

	xcode-project use-profiles

          xcodebuild \
            -project ios/App/App.xcodeproj \
            -scheme App \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/App.xcarchive \
            DEVELOPMENT_TEAM="${TEAM_ID}" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            PROVISIONING_PROFILE="${PROFILE_UUID}" \
            archive

      - name: Export IPA
        script: |
          set -euo pipefail
          cat > exportOptions.plist <<EOF
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>app-store</string>
            <key>teamID</key>
            <string>${TEAM_ID}</string>
            <key>signingStyle</key>
            <string>manual</string>
          </dict>
          </plist>
          EOF


          xcodebuild \
            -exportArchive \
            -archivePath build/App.xcarchive \
            -exportOptionsPlist exportOptions.plist \
            -exportPath build/export

    artifacts:
      - build/export/*.ipa
      - build/**/*.xcarchive
      - exportOptions.plist
